import React, { useEffect, useMemo, useState } from "react";
import API_BASE_URL from "../config";
import "../components/FtpLogs.css";

const PRIORITY_META = {
  critical: { label: "CRITICAL", bg: "rgba(239,68,68,0.25)", fg: "#fff", border: "rgba(239,68,68,0.55)" },
  high: { label: "HIGH", bg: "rgba(249,115,22,0.22)", fg: "#fff", border: "rgba(249,115,22,0.55)" },
  medium: { label: "MEDIUM", bg: "rgba(234,179,8,0.20)", fg: "#fff", border: "rgba(234,179,8,0.55)" },
  low: { label: "LOW", bg: "rgba(59,130,246,0.18)", fg: "#fff", border: "rgba(59,130,246,0.55)" },
};

function Badge({ label, bg, fg, border }) {
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        height: 26,
        padding: "0 10px",
        borderRadius: 999,
        fontSize: 12,
        fontWeight: 800,
        letterSpacing: "0.4px",
        textTransform: "uppercase",
        border: `1px solid ${border || "rgba(148,163,184,0.18)"}`,
        background: bg || "rgba(148,163,184,0.08)",
        color: fg || "rgba(226,232,240,0.92)",
        whiteSpace: "nowrap",
      }}
    >
      {label}
    </span>
  );
}

function PriorityBadge({ priority }) {
  const p = String(priority || "").toLowerCase();
  const meta =
    PRIORITY_META[p] || {
      label: p || "—",
      bg: "rgba(107,114,128,0.25)",
      fg: "#fff",
      border: "rgba(107,114,128,0.55)",
    };

  return <Badge label={meta.label} bg={meta.bg} fg={meta.fg} border={meta.border} />;
}

function StatusBadge({ status }) {
  const s = String(status || "new").toLowerCase();

  const meta =
    s === "resolved"
      ? { label: "RESOLVED", bg: "rgba(34,197,94,0.18)", fg: "#fff", border: "rgba(34,197,94,0.45)" }
      : s === "acknowledged"
        ? { label: "ACK", bg: "rgba(56,189,248,0.18)", fg: "#fff", border: "rgba(56,189,248,0.55)" }
        : { label: "NEW", bg: "rgba(148,163,184,0.18)", fg: "#fff", border: "rgba(148,163,184,0.45)" };

  return <Badge label={meta.label} bg={meta.bg} fg={meta.fg} border={meta.border} />;
}

function formatDateTime(createdAt) {
  if (!createdAt) return "—";
  const dt = new Date(createdAt);
  if (Number.isNaN(dt.getTime())) return String(createdAt);
  return dt.toLocaleString();
}

function getInvestigationSummary(alert) {
  const priority = String(alert?.priority || "").toLowerCase();

  if (priority === "critical") {
    return "Critical alert requiring immediate analyst review. Investigate the linked evidence and validate whether this is an active attack.";
  }

  if (priority === "high") {
    return "High priority suspicious activity with correlated evidence. Review source behavior, affected service, and repeated activity.";
  }

  if (priority === "medium") {
    return "Medium priority alert generated by the detection logic. Review linked logs to confirm whether escalation is needed.";
  }

  return "Alert generated by Raven detection logic. Review the linked evidence below for context.";
}

export default function AlertsPage({ refreshTrigger }) {
  const [items, setItems] = useState([]);
  const [total, setTotal] = useState(0);

  const [priority, setPriority] = useState("all");
  const [status, setStatus] = useState("all");
  const [q, setQ] = useState("");
  const [includeInternal, setIncludeInternal] = useState(true);

  const [page, setPage] = useState(1);
  const limit = 20;

  const [selectedId, setSelectedId] = useState(null);
  const [details, setDetails] = useState(null);
  const [detailsLoading, setDetailsLoading] = useState(false);

  const totalPages = useMemo(() => {
    if (!total) return 1;
    return Math.max(1, Math.ceil(total / limit));
  }, [total]);

  async function fetchAlerts() {
    const params = new URLSearchParams();
    params.set("page", String(page));
    params.set("limit", String(limit));

    if (priority !== "all") params.set("priority", priority);
    if (status !== "all") params.set("status", status);
    if (q.trim()) params.set("q", q.trim());

    params.set("include_internal", includeInternal ? "1" : "0");

    const res = await fetch(`${API_BASE_URL}/api/alerts?${params.toString()}`);
    if (!res.ok) throw new Error(`Failed to fetch alerts: ${res.status}`);

    const data = await res.json();
    setItems(data.items || []);
    setTotal(data.total || 0);
  }

  async function fetchAlertDetails(alertId) {
    setDetailsLoading(true);
    setDetails(null);

    try {
      const res = await fetch(`${API_BASE_URL}/api/alerts/${alertId}`);
      if (!res.ok) throw new Error(`Failed to fetch alert details: ${res.status}`);

      const data = await res.json();
      setDetails(data);
    } finally {
      setDetailsLoading(false);
    }
  }

  async function updateStatus(alertId, newStatus) {
    const res = await fetch(`${API_BASE_URL}/api/alerts/${alertId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: newStatus }),
    });

    if (!res.ok) {
      const txt = await res.text();
      throw new Error(`Failed to update status (${res.status}): ${txt}`);
    }

    await fetchAlerts();

    if (selectedId === alertId) {
      await fetchAlertDetails(alertId);
    }
  }

  function exportCsv(alertId) {
    window.open(`${API_BASE_URL}/api/alerts/${alertId}/export_csv`, "_blank");
  }

  useEffect(() => {
    fetchAlerts().catch((e) => console.error(e));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [page, priority, status, includeInternal, refreshTrigger]);

  useEffect(() => {
    setPage(1);
  }, [priority, status, q, includeInternal]);

  useEffect(() => {
    if (selectedId == null) return;
    fetchAlertDetails(selectedId).catch((e) => console.error(e));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedId]);

  return (
    <div className="content">
      <div className="card">
        <div className="card-header">
          <div>
            <h2 className="card-title">🚨 Alerts</h2>
            <div className="card-subtitle">Security alerts + linked evidence</div>
          </div>

          <button
            className="btn btn-secondary"
            type="button"
            onClick={() => fetchAlerts().catch((e) => console.error(e))}
          >
            Refresh
          </button>
        </div>

        <div className="filters-row">
          <input
            className="input"
            value={q}
            onChange={(e) => setQ(e.target.value)}
            placeholder="Search title/description..."
          />

          <select className="select" value={priority} onChange={(e) => setPriority(e.target.value)}>
            <option value="all">All priorities</option>
            <option value="critical">Critical</option>
            <option value="high">High</option>
            <option value="medium">Medium</option>
            <option value="low">Low</option>
          </select>

          <select className="select" value={status} onChange={(e) => setStatus(e.target.value)}>
            <option value="all">All status</option>
            <option value="new">New</option>
            <option value="acknowledged">Acknowledged</option>
            <option value="resolved">Resolved</option>
          </select>

          <label
            style={{
              display: "flex",
              alignItems: "center",
              gap: 10,
              height: 40,
              padding: "0 12px",
              borderRadius: 10,
              border: "1px solid rgba(148, 163, 184, 0.22)",
              background: "rgba(2, 6, 23, 0.55)",
              color: "rgba(226, 232, 240, 0.85)",
              userSelect: "none",
              whiteSpace: "nowrap",
            }}
            title="Include alerts from 127.0.0.1 / ::1"
          >
            <input
              type="checkbox"
              checked={includeInternal}
              onChange={(e) => setIncludeInternal(e.target.checked)}
              style={{ accentColor: "#38bdf8" }}
            />
            Show internal
          </label>

          <button
            className="btn btn-secondary"
            type="button"
            onClick={() => {
              setPriority("all");
              setStatus("all");
              setQ("");
              setIncludeInternal(true);
              setSelectedId(null);
              setDetails(null);
              setPage(1);
            }}
          >
            Clear
          </button>
        </div>

        <div
          className="alerts-layout"
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 420px",
            gap: 16,
            marginTop: 10,
          }}
        >
          <div className="table-wrap">
            <table className="table" style={{ minWidth: 860 }}>
              <thead>
                <tr>
                  <th style={{ width: 180 }}>TIME</th>
                  <th style={{ width: 120 }}>PRIORITY</th>
                  <th style={{ width: 140 }}>STATUS</th>
                  <th>TITLE</th>
                  <th style={{ width: 310, textAlign: "right" }}>ACTIONS</th>
                </tr>
              </thead>

              <tbody>
                {items.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="empty">
                      No alerts match your filters.
                    </td>
                  </tr>
                ) : (
                  items.map((a) => {
                    const active = selectedId === a.id;

                    return (
                      <tr
                        key={a.id}
                        onClick={() => setSelectedId(a.id)}
                        style={{
                          cursor: "pointer",
                          background: active ? "rgba(56, 189, 248, 0.06)" : undefined,
                        }}
                        title={a.description || ""}
                      >
                        <td className="mono">{formatDateTime(a.created_at)}</td>

                        <td>
                          <PriorityBadge priority={a.priority} />
                        </td>

                        <td>
                          <StatusBadge status={a.status} />
                        </td>

                        <td style={{ fontWeight: 800 }}>{a.title}</td>

                        <td>
                          <div style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}>
                            <button
                              className="btn btn-secondary"
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                setSelectedId(a.id);
                              }}
                              style={{ height: 34, padding: "0 12px" }}
                            >
                              View
                            </button>

                            <button
                              className="btn btn-secondary"
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                updateStatus(a.id, "acknowledged").catch((err) => alert(err.message));
                              }}
                              style={{ height: 34, padding: "0 12px" }}
                            >
                              Ack
                            </button>

                            <button
                              className="btn btn-secondary"
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                updateStatus(a.id, "resolved").catch((err) => alert(err.message));
                              }}
                              style={{ height: 34, padding: "0 12px" }}
                            >
                              Resolve
                            </button>

                            <button
                              className="btn btn-secondary"
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                exportCsv(a.id);
                              }}
                              style={{ height: 34, padding: "0 12px" }}
                            >
                              Export CSV
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>

            <div className="pager" style={{ padding: 12 }}>
              <button
                className="btn btn-secondary"
                disabled={page <= 1}
                onClick={() => setPage((p) => Math.max(1, p - 1))}
              >
                Prev
              </button>

              <div style={{ color: "rgba(226,232,240,0.75)", fontSize: 13 }}>
                Total: <b>{total}</b> — Page <b>{page}</b> / <b>{totalPages}</b>
              </div>

              <button
                className="btn btn-secondary"
                disabled={page >= totalPages}
                onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              >
                Next
              </button>
            </div>
          </div>

          <div className="card" style={{ padding: 14 }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10 }}>
              <div>
                <div style={{ fontSize: 18, fontWeight: 800, color: "#e2e8f0" }}>
                  Alert Investigation
                </div>
                <div style={{ marginTop: 4, fontSize: 13, color: "rgba(226,232,240,0.7)" }}>
                  Case view with linked evidence
                </div>
              </div>

              {selectedId != null && (
                <button
                  className="btn btn-secondary"
                  type="button"
                  onClick={() => fetchAlertDetails(selectedId).catch((e) => console.error(e))}
                  style={{ height: 34, padding: "0 12px" }}
                >
                  Refresh
                </button>
              )}
            </div>

            {selectedId == null ? (
              <div style={{ color: "rgba(226,232,240,0.65)", marginTop: 14 }}>
                Select an alert to view linked evidence.
              </div>
            ) : detailsLoading ? (
              <div style={{ marginTop: 14, color: "rgba(226,232,240,0.85)" }}>
                Loading…
              </div>
            ) : !details ? (
              <div style={{ color: "rgba(226,232,240,0.65)", marginTop: 14 }}>
                No details loaded.
              </div>
            ) : (
              <div style={{ marginTop: 14 }}>
                <div style={{ fontSize: 12, color: "rgba(226,232,240,0.65)" }}>
                  ALERT
                </div>

                <div style={{ fontWeight: 900, marginTop: 6, color: "#e2e8f0" }}>
                  {details.alert?.title}
                </div>

                <div style={{ marginTop: 8, fontSize: 13, color: "rgba(226,232,240,0.85)" }}>
                  {details.alert?.description}
                </div>

                <div className="alert-case-box">
                  <div className="alert-case-title">Investigation Summary</div>

                  <div className="alert-case-text">
                    {getInvestigationSummary(details.alert)}
                  </div>

                  <div className="alert-case-chips">
                    <span className="alert-chip">
                      Rule: {details.alert?.source || "Detection Rule"}
                    </span>

                    <span className="alert-chip">
                      Priority: {details.alert?.priority || "—"}
                    </span>

                    <span className="alert-chip">
                      Evidence: {(details.linked_items || []).length}
                    </span>
                  </div>
                </div>

                <div style={{ marginTop: 14, fontSize: 12, color: "rgba(226,232,240,0.65)" }}>
                  LINKED EVIDENCE
                </div>

                <div className="alerts-grid" style={{ marginTop: 10, display: "grid", gap: 10 }}>
                  {(details.linked_items || []).map((it, idx) => (
                    <div
                      key={idx}
                      style={{
                        border: "1px solid rgba(148, 163, 184, 0.14)",
                        borderRadius: 12,
                        padding: 12,
                        background: "rgba(2, 6, 23, 0.25)",
                      }}
                    >
                      <div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}>
                        <div style={{ fontWeight: 900, fontSize: 13, color: "#e2e8f0" }}>
                          {it.log_type || "Evidence"}
                        </div>

                        <div className="mono" style={{ fontSize: 12, color: "rgba(226,232,240,0.7)" }}>
                          {it.time || "—"}
                        </div>
                      </div>

                      <div style={{ marginTop: 8, fontSize: 12, color: "rgba(226,232,240,0.85)" }}>
                        <div className="evidence-tags">
                          <span className="evidence-tag">
                            Source: {it.source || "—"}
                          </span>

                          <span className="evidence-tag">
                            Type: {it.log_type || "—"}
                          </span>
                        </div>

                        <div style={{ marginTop: 6, whiteSpace: "pre-wrap" }}>
                          <b>Message:</b> {it.message || "—"}
                        </div>
                      </div>
                    </div>
                  ))}

                  {(!details.linked_items || details.linked_items.length === 0) && (
                    <div style={{ color: "rgba(226,232,240,0.65)" }}>
                      No linked items.
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>

        <div
          style={{
            marginTop: 12,
            color: "rgba(226,232,240,0.55)",
            fontSize: 12,
            display: "none",
          }}
        />
      </div>
    </div>
  );
}